---
abstract: 'Useful helpers on top of POSIX::1003'
author:
  - 'Mark Overmeer'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POSIX-Util
no_index:
  directory:
    - t
    - inc
requires:
  POSIX::1003: 0.13
  Test::More: 0.47
version: 0.10
